// Shim → re-export from new SQLite-based DB layer (src/lib/db/)
// Kept for backward compatibility with existing imports.
export {
  getSettings, updateSettings, isCloudEnabled, getCloudUrl,
  getProviderConnections, getProviderConnectionById,
  createProviderConnection, updateProviderConnection,
  deleteProviderConnection, deleteProviderConnectionsByProvider,
  reorderProviderConnections, cleanupProviderConnections,
  getProviderNodes, getProviderNodeById,
  createProviderNode, updateProviderNode, deleteProviderNode,
  getProxyPools, getProxyPoolById,
  createProxyPool, updateProxyPool, deleteProxyPool,
  getApiKeys, getApiKeyById, getApiKeyByKey, createApiKey, updateApiKey, deleteApiKey, validateApiKey,
  getOrganizations, getOrganizationsForUser, getOrganizationById,
  createOrganization, updateOrganization, setOrganizationStatus, deleteOrganization,
  getUserById, getUserByEmail, createUser, updateUser,
  recordUserLogin, verifyUserPassword, upsertSsoUser, registerUserWithBootstrapping,
  getMembershipsForUser, getMembershipsForOrg, getMembership,
  addMembership, updateMembershipRole, removeMembership,
  createInvitation, getInvitationByCode, getInvitationsForOrg,
  redeemInvitation, revokeInvitation,
  getSuperadminByUsername, verifySuperadminPassword, updateSuperadminPassword, seedSuperadmin,
  getOrgSettings, updateOrgSettings, deleteOrgSettings,
  getOrgCurrentMonthlySpend,
  getCombos, getComboById, getComboByName,
  createCombo, updateCombo, deleteCombo,
  getModelAliases, setModelAlias, deleteModelAlias,
  getCustomModels, addCustomModel, deleteCustomModel,
  getMitmAlias, setMitmAliasAll,
  getPricing, getPricingForModel, updatePricing, resetPricing, resetAllPricing,
  exportDb, importDb,
} from "@/lib/db/index.js";
